/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "Driver_Watchdog.h"
#include "Driver_Stm.h"
#include "Driver_Port.h"
#include "Driver_Adc.h"
#include "Driver_Asc.h"
#include "Driver_Gtm.h"
#include "Driver_Can.h"

#include "SharedVariables.h"   // ── CPU0 ↔ CPU1 Shared 메모리 정의 (iq, position, processingFlag 등)
#include "Subsystem.h"         // ── Simulink에서 생성된 서브시스템 헤더
#include "rtwtypes.h"          // ── Simulink 타입 정의 (real_T, real32_T 등)

#include "AppScheduling.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

int core1_main(void)
{
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * 필요 시 Watchdog을 활성화하고 주기적으로 서비스해 줍니다.
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /*******************************
     * Simulink 모델 초기화
     *******************************/
    Subsystem_initialize();  // Delay 블록 초기화 포함

    /*
     * 반복 주기 (예: 1ms 혹은 여러분이 설정한 샘플 타임)에 맞춰
     * processingFlag가 1로 올라오면 모델 스텝 실행
     */
    while (1)
    {
        /* CPU0에서 CAN 데이터를 받아 SharedVariables에 쓰면 processingFlag = 1로 설정됨.
         * CPU1은 이 신호가 1이 되면 아래 루틴 수행 후 다시 0으로 리셋
         */
        if (processingFlag == 1)
        {
//            /*************************************
//             * 1) 전역 변수에서 최신 CAN 데이터 읽기
//             *    (CPU0가 업데이트해 둔 iq, position 등을 가져옴)
//             *************************************/
//            double in1_val = (double)iq;          // 예: CAN으로 받은 iq
//            double in2_val = (double)position;    // 예: CAN으로 받은 position

            /*************************************
             * 2) Simulink 모델 입력 버퍼에 대입
             *    rtU.In1, rtU.In2에 실수(double)형으로 넣어 줌
             *************************************/
            rtU.In1 = IQ;   // Subsystem.h에 extern ExtU rtU; 내부 In1 멤버
            rtU.In2 = POS;   // Subsystem.h에 extern ExtU rtU; 내부 In2 멤버

            /*************************************
             * 3) 모델 스텝 실행
             *    내부 Delay가 과거 3스텝을 자동으로 관리하여
             *    총 4쌍(8개 값)으로 계산해 줌
             *************************************/
            Subsystem_step();

            /*************************************
             * 4) 모델 출력 읽기
             *    Subsystem.h에 extern ExtY rtY; 내부 output 멤버
             *************************************/
            float modelOutput = rtY.output;

            /*************************************
             * 5) 모델 결과(modelOutput) 처리
             *    예를 들면, 다른 전역 변수에 저장하거나
             *    DAC/PWM으로 출력, CAN 송신 등
             *************************************/
            // 예시: 결과를 다른 전역 변수에 저장
            processedValue = modelOutput;  // SharedVariables.h에 추가 정의했다고 가정

            /*************************************
             * 6) 처리 완료 신호 리셋
             *************************************/
            processingFlag = 0;
        }

        /* 필요 시 idle 상태에서 WFI 명령 등 삽입 가능 */
    }

    return (1);
}
